<?php
    session_start(); //Starting the session
    $id = session_id(); //Random session id generated by php
    echo "Session id: ",$id;
    
    $_SESSION ["session_id"]=1111;
    echo "<br> Your session id is: ".$_SESSION["session_id"];

    $_SESSION["login_id"]=5017;
    echo "<br> Your login id is: ".$_SESSION["login_id"];

    //Counting number of visits in a single session
    if(isset($_SESSION["counter"]))
    {
        $_SESSION["counter"] += 1;
    }
    else
    {
        $_SESSION["counter"] = 1;
    }
    echo "<br> Number of visits in this session: ".$_SESSION["counter"];

    session_destroy(); //To destroy a session
?>
/*
&lt;?php
// Starting the session
session_start();
// Assigning a sample login ID to session (for demonstration)
$_SESSION[&quot;loginid&quot;] = 5017;
// Retrieving and displaying the session variable
if (isset($_SESSION[&quot;loginid&quot;])) {
echo &quot;&lt;p&gt;Your Login ID is: &quot; . $_SESSION[&quot;loginid&quot;] . &quot;&lt;/p&gt;&quot;;
} else {

echo &quot;&lt;p&gt;Session variable &#39;loginid&#39; is not set.&lt;/p&gt;&quot;;
}
?&gt;
*/